### ISSUE TITLE
Document helm usage 

### ISSUE THREAD

**Issue by saiyam1814** [stackrox/kube-linter#21]
any help usage example ?

**Comment by viswajithiii** [comment]
Hi @saiyam1814, you can run `kube-linter lint <dir>` where `<dir>` is a path to a Helm chart (ie, it contains a `Chart.yaml`).

I will update our documentation to make this more clear, but in the meantime, let me know if this answers your question.

**Comment by saiyam1814** [comment]
I pointed to the directory but it still  shows yaml errors I mean how different the helm chart check is 
I have below in the repo 
![image](https://user-images.githubusercontent.com/8190114/97679613-7e978d80-1abb-11eb-891a-5cf7c5bbd03a.png)
I do kube-linter lint . 
I checks the yaml file like it usually do.

**Comment by kreamkorokke** [comment]
@saiyam1814 as of now we actually just started supporting helm, and the errors are reported on the parsed yaml files. So right now the check output will look the same for plain k8s manifests and helm.

I will make sure to communicate this with our main developer as he is out now, and thanks again for pointing this out.

**Comment by viswajithiii** [comment]
@saiyam1814 `kube-linter lint .` renders the templates in the Helm chart using the `values.yaml` file, and runs the checks on the rendered YAMLs. The checks that are actually run are the same as the checks run on the rendered YAML files. Thus, `kubelinter lint .` on a Helm chart directory is functionally equivalent to something like: `helm template . --output-dir /tmp/chart; kube-linter lint /tmp/chart`. If `kube-linter lint` did not do the rendering, it would try to lint the template files directly, which would not work since they are not valid YAMLs. Does that make sense? What is the behaviour you expected to see?

Also, see https://github.com/stackrox/kube-linter/issues/48 for some proposed improvements to our Helm support.

**Comment by saiyam1814** [comment]
Thanks, I wrote a short blog the other day after kubeLinter was announced. 
https://www.civo.com/learn/yaml-best-practices-using-kubelinter

**Comment by viswajithiii** [comment]
> Thanks, I wrote a short blog the other day after kubeLinter was announced.
> https://www.civo.com/learn/yaml-best-practices-using-kubelinter

Thanks @saiyam1814! That is a great blog. I will add a link to it in our README. 🙂
