### ISSUE TITLE
go get kube-linter wrong

### ISSUE THREAD

**Issue by JacksonRin** [stackrox/kube-linter#22]
when I excute "golang.stackrox.io/kube-linter/cmd/kube-linter" on linux，there is a error like:go: github.com/Masterminds/sprig/v3@v3.1.0: Get "https://proxy.golang.org/github.com/%21masterminds/sprig/v3/@v/v3.1.0.mod": x509: certificate signed by unknown authority
how can I solve this problem

**Comment by viswajithiii** [comment]
Hi @JacksonRin, thanks for filing an issue!

This looks like you need to update your CA certificates, since your system doesn't trust https://proxy.golang.org. If you're on alpine, you can do `apk add ca-certificates`. You can also try bypassing the golang proxy by running `go env -w GOPROXY=direct` before running this. If that doesn't work either, it's possible there's a man-in-the-middle proxy in your environment that's intercepting TLS connections? In that case, my recommendation would be to just download the precompiled binary.

See https://github.com/golang/go/issues/35702 for other potential fixes.

**Comment by JacksonRin** [comment]
thanks for reply,I'll try to download the precompiled binary,thanks again.

**Comment by viswajithiii** [comment]
Sounds good! Closing this issue.
